# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

project:
  name: Greenhouse
  tz: Europe/Berlin
  adrFolder: architecture-decision-records
  packages: []
